-- use customer_behavior_db;
select * from customers;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as total_revenue
from customers
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount 
from customers 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customers);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as total_ratings
from customers 
group by item_purchased 
order by total_ratings desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(avg(purchase_amount),2) as total_amount
from customers 
where shipping_type in ('Standard' ,'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
select subscription_status,round(avg(purchase_amount),2) as avg_revenue,
sum(purchase_amount) as total_revenue
from customers 
group by subscription_status
order by avg_revenue,total_revenue desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100.0*sum(case when discount_applied ='Yes' then 1 else 0 end )/count(*),2) as discount_rate
from customers 
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id ,previous_purchases,
case when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning' 
else 'Loyal' end as customer_segment
from customers
)
select customer_segment,count(*) as 'Number of Customers'
from customer_type 
group by customer_segment;

-- Q8. What are the top 3 most purchased products within each category? 
with items_count as (
select category,item_purchased,count(*) as total_orders,
row_number() over(partition by category order by  count(customer_id) desc ) as rk 
from customers
group by category,item_purchased
)
select category,item_purchased,total_orders
from items_count 
where rk<=3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_customers
from customers
where previous_purchases >5
group by subscription_status;

-- Q10. What is the revenue contribution of each age group? 
select gender,sum(purchase_amount) as reveune
from customers
group by gender 
order by reveune desc;